### ISSUE TITLE
Put https://ikod.github.io/ikod-containers/ikod.containers.html on the README and/or github about

### ISSUE THREAD

**Issue by Zardoz89** [ikod/ikod-containers#4]
Put https://ikod.github.io/ikod-containers/ikod.containers.html on the README and/or github about

**Comment by ikod** [comment]
hello, @Zardoz89 

ok, thanks!

**Comment by ikod** [comment]
Hi @Zardoz89 

should be ok now

**Comment by Zardoz89** [comment]
Thanks!
